### Validation
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "master",
  "age": 10,
  "email": "master@gamil.com",
  "phoneNumber": "010-1111-2222",
  "reqYearMonth": "a111111"
}
