### Validation
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "master",
  "age": 10,
  "email": "master@gamil.com",
  "phoneNumber": "010-1111-2222",
  "reqYearMonth": "111111",
  "cars": [
    {
      "name": "K5",
      "car_number": "",
      "TYPE": ""
    },
    {
      "name": "Q5",
      "car_number": "",
      "TYPE": ""
    }
  ]
}
